# The file is generated by:
#   $args
let
  lib = import ../../common/lib.nix;

  version = "$version";
  hash = "$hash";

  # $rust_toolchain_url
  rustVersion = "$rust_version";
  cargoLock = {
    # $cargo_lock_url
    lockFile = ./Cargo.lock;
    outputHashes = {
      $output_hashes
    };
  };
in
  lib.makePants {
    inherit version hash rustVersion cargoLock;
  }
